-- Platform-owned tables for shared app concerns.
-- Keep tracker-specific data out of this schema area.
--
-- Apply the migration in:
-- supabase/migrations/20260603123000_platform_schema.sql
--
-- Tracker-specific tables live separately inside each module. Do not add a
-- generic template builder, generic custom fields, or generic records table.
